name: Check Update
on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          ref: 'master'
          path: 'master'
      - name: Check update
        uses: gradle/gradle-build-action@v2
        with:
          arguments: checkUpdate
      - name: Check Result
        runs: |
          ls eden
          ls master/android_pad
          echo "UPDATE_FLAG=$(expr cat commit_flag)" >> $GITHUB_ENV
          echo "UPDATE_LENGTH=$(expr length "$UPDATE_FLAG")" >> $GITHUB_ENV
      - name: Push commit
        if: ${{ env.UPDATE_LENGTH > 0 }}
        runs: |
          cd master
          git add .
          git commit -m "Auto update ${{ env.UPDATE_FLAG }}"
          git push
